# Generated by Django 5.2.5 on 2025-08-28 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Travel_Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bus", "bus"),
                            ("train", "train"),
                            ("Flight", "Flight"),
                        ],
                        max_length=10,
                    ),
                ),
                ("From", models.CharField(max_length=100)),
                ("To", models.CharField(max_length=100)),
                ("date_time", models.DateTimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=4)),
                ("available_seats", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="booking",
            fields=[
                ("booking_id", models.AutoField(primary_key=True, serialize=False)),
                ("seats", models.PositiveIntegerField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("confirmed", "confirmed"), ("failed", "Failed")],
                        default="Confirmed",
                        max_length=10,
                    ),
                ),
                (
                    "users",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "travel_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookings.travel_option",
                    ),
                ),
            ],
        ),
    ]
