# Generated by Django 5.2.5 on 2025-08-28 22:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travel_option",
            name="date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="travel_option",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
